Organizations:
    - &OrdererOrg1
        Name: OrdererOrg1MSP
        ID: OrdererOrg1MSP
        MSPDir: crypto-config/ordererOrganizations/org1.foo.com/msp

    - &OrdererOrg2
        Name: OrdererOrg2MSP
        ID: OrdererOrg2MSP
        MSPDir: crypto-config/ordererOrganizations/org2.foo.com/msp

    - &OrdererOrg3
        Name: OrdererOrg3MSP
        ID: OrdererOrg3MSP
        MSPDir: crypto-config/ordererOrganizations/org3.foo.com/msp

    - &PeerOrg1
        Name: PeerOrg1MSP
        ID: PeerOrg1MSP
        MSPDir: crypto-config/peerOrganizations/org1.foo.com/msp
        AnchorPeers:
            - Host: peer0.org1.foo.com
              Port: 7051
            - Host: peer1.org1.foo.com
              Port: 7051

    - &PeerOrg2
        Name: PeerOrg2MSP
        ID: PeerOrg2MSP
        MSPDir: crypto-config/peerOrganizations/org2.foo.com/msp
        AnchorPeers:
            - Host: peer0.org2.foo.com
              Port: 7051
            - Host: peer1.org2.foo.com
              Port: 7051

    - &PeerOrg3
        Name: PeerOrg3MSP
        ID: PeerOrg3MSP
        MSPDir: crypto-config/peerOrganizations/org3.foo.com/msp
        AnchorPeers:
            - Host: peer0.org3.foo.com
              Port: 7051
            - Host: peer1.org3.foo.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
        - orderer0.org1.foo.com:7050
        - orderer1.org1.foo.com:7050
        - orderer0.org2.foo.com:7050
        - orderer1.org2.foo.com:7050
        - orderer0.org3.foo.com:7050
        - orderer1.org3.foo.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - kafka0:9092
            - kafka1:9092
            - kafka2:9092
            - kafka3:9092
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg1
                - *OrdererOrg2
                - *OrdererOrg3
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *PeerOrg1
                    - *PeerOrg2
                    - *PeerOrg3
    Channel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PeerOrg1
                - *PeerOrg2
                - *PeerOrg3

