version: '2'

services:
  ca.org1.foo.com:
    image: hyperledger/fabric-ca:x86_64-1.0.0
    container_name: ca.org1.foo.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.foo.com
#      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/org1.foo.com-cert.pem
#      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a22daf356b2aab5792ea53e35f66fccef1d7f1aa2b3a2b92dbfbf96a448ea26a_sk

    ports:
      - "7054:7054"
    # ls -la ../001-generatecrypto/fabric-ca-config/
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/03303662df971240c18263ee2444703d22c55084cf7c63c4b4f1a4f4b2d0ddc2_sk -b admin:adminpw -d'
    volumes:
      - ../001-generatecrypto/fabric-ca-config/:/etc/hyperledger/fabric-ca-server-config

  orderer.foo.com:
    image: hyperledger/fabric-orderer:x86_64-1.0.0
    container_name: orderer.foo.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ../002-generategenesis:/etc/hyperledger/configtx
        - ../001-generatecrypto/fabric-orderer-config/msp:/etc/hyperledger/msp/orderer/msp

  peer0.org1.foo.com:
    image: hyperledger/fabric-peer:x86_64-1.0.0
    container_name: peer0.org1.foo.com
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.foo.com
      - CORE_PEER_ADDRESS=peer0.org1.foo.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../002-generategenesis:/etc/hyperledger/configtx        
        - ../001-generatecrypto/fabric-peer-config/msp:/etc/hyperledger/peer/msp
        - ../001-generatecrypto/fabric-peer-config/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.foo.com
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:x86_64-1.0.0
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db


